[build]
# Command to build your Go app
cmd = "go build -o ./tmp/main.exe ."

# Add .\ so PowerShell knows it's an executable
bin = ".\\tmp\\main.exe"

include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "tmp"]
delay = 1000
log = "air.log"
